# Generated by Django 4.2.7 on 2023-11-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('period', models.CharField(max_length=70)),
                ('technologies', models.ManyToManyField(to='project.tech')),
            ],
        ),
    ]
