# Generated by Django 4.2.7 on 2023-11-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='tech_images/'),
        ),
    ]
