# Generated by Django 4.2.7 on 2023-11-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_tech_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='type',
            field=models.CharField(blank=True, choices=[('Leguage', 'Leguage'), ('Frameworks', 'Frameworks'), ('Tools', 'Tools'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
